import { Application, CandidateProfile, Job } from "./types";

/**
 * Beispieldaten, damit das Frontend ohne Supabase-Anbindung lauffähig ist.
 * Sobald `lib/supabase` eingerichtet ist, können diese Funktionen durch
 * echte DB-Queries ersetzt werden (siehe TODOs in den jeweiligen Seiten).
 */

export const MOCK_JOBS: Job[] = [
  {
    id: "1",
    source: "jobsimsport",
    externalId: "jis-1001",
    sourceUrl: "https://jobsimsport.de/jobs/1001",
    companyUrl: null,
    title: "Athletiktrainer (m/w/d) Nachwuchsleistungszentrum Fußball",
    company: "1. FC Beispielstadt",
    location: "Köln",
    employmentType: "vollzeit",
    category: "Fußball",
    tags: ["Athletiktraining", "NLZ", "A-Lizenz", "Reha"],
    description:
      "Für unser Nachwuchsleistungszentrum suchen wir einen erfahrenen Athletiktrainer, der die U17 bis U19 Mannschaften betreut. Du verantwortest die Trainingsplanung im Bereich Kraft, Schnelligkeit und Verletzungsprävention.",
    salaryRange: "45.000 - 55.000 € / Jahr",
    postedAt: "2026-06-10",
    scrapedAt: "2026-06-14T06:00:00Z",
    isActive: true,
  },
  {
    id: "2",
    source: "dshs_koeln",
    externalId: "dshs-552",
    sourceUrl: "https://jobs.dshs-koeln.de/jobs/552",
    companyUrl: null,
    title: "Wissenschaftliche*r Mitarbeiter*in Sportpsychologie",
    company: "Deutsche Sporthochschule Köln",
    location: "Köln",
    employmentType: "vollzeit",
    category: "Wissenschaft & Forschung",
    tags: ["Sportpsychologie", "Forschung", "Lehre", "Promotion"],
    description:
      "Im Rahmen eines Drittmittelprojekts ist eine Stelle als wissenschaftliche Mitarbeiterin / wissenschaftlicher Mitarbeiter im Institut für Sportpsychologie zu besetzen. Mitarbeit in Lehre und Forschung, Möglichkeit zur Promotion.",
    salaryRange: "TV-L 13, 75%",
    postedAt: "2026-06-12",
    scrapedAt: "2026-06-14T06:00:00Z",
    isActive: true,
  },
  {
    id: "3",
    source: "spobis_jobs",
    externalId: "spobis-9981",
    sourceUrl: "https://www.spobis-jobs.com/jobs/9981",
    companyUrl: null,
    title: "Marketing Manager (m/w/d) Sportartikelhersteller",
    company: "ActiveGear GmbH",
    location: "München",
    employmentType: "vollzeit",
    category: "Marketing",
    tags: ["Brand Management", "Social Media", "Sportartikel", "Kampagnen"],
    description:
      "Du entwickelst und steuerst Marketingkampagnen für unsere Outdoor- und Laufsport-Kollektionen, arbeitest eng mit Athleten und Influencern zusammen und verantwortest den Social-Media-Auftritt.",
    salaryRange: null,
    postedAt: "2026-06-09",
    scrapedAt: "2026-06-14T06:00:00Z",
    isActive: true,
  },
  {
    id: "4",
    source: "sport_job",
    externalId: "sj-44210",
    sourceUrl: "https://www.sport-job.com/jobs/44210",
    companyUrl: null,
    title: "Eventmanager (m/w/d) für Laufveranstaltungen",
    company: "RunEvents AG",
    location: "Hamburg",
    employmentType: "vollzeit",
    category: "Eventmanagement",
    tags: ["Eventplanung", "Laufsport", "Sponsoring", "Logistik"],
    description:
      "Planung und Durchführung von Laufveranstaltungen (5km bis Marathon) inklusive Streckenplanung, Genehmigungen, Sponsorenmanagement und Teamführung am Veranstaltungstag.",
    salaryRange: "40.000 - 48.000 € / Jahr",
    postedAt: "2026-06-08",
    scrapedAt: "2026-06-14T06:00:00Z",
    isActive: true,
  },
  {
    id: "5",
    source: "joborama",
    externalId: "joborama-77123",
    sourceUrl: "https://www.joborama.de/jobs/77123",
    companyUrl: null,
    title: "Physiotherapeut (m/w/d) für Profi-Basketballteam",
    company: "Baskets Beispielstadt e.V.",
    location: "Stuttgart",
    employmentType: "teilzeit",
    category: "Physiotherapie",
    tags: ["Physiotherapie", "Basketball", "Reha", "Profisport"],
    description:
      "Betreuung der ersten Mannschaft während Training und Spielen, Erstellung von Reha-Plänen nach Verletzungen, enge Zusammenarbeit mit dem medizinischen Stab.",
    salaryRange: null,
    postedAt: "2026-06-11",
    scrapedAt: "2026-06-14T06:00:00Z",
    isActive: true,
  },
  {
    id: "6",
    source: "jobsimsport",
    externalId: "jis-1050",
    sourceUrl: "https://jobsimsport.de/jobs/1050",
    companyUrl: null,
    title: "Werkstudent (m/w/d) Social Media & Content",
    company: "Handball Bundesliga GmbH",
    location: "Remote / Dortmund",
    employmentType: "werkstudent",
    category: "Marketing",
    tags: ["Social Media", "Content Creation", "Handball", "Remote"],
    description:
      "Unterstützung des Social-Media-Teams bei der Erstellung von Content rund um die Handball Bundesliga, Community-Management und Auswertung von Reichweiten-KPIs.",
    salaryRange: "14 € / Stunde",
    postedAt: "2026-06-13",
    scrapedAt: "2026-06-14T06:00:00Z",
    isActive: true,
  },
];

export const MOCK_CANDIDATE: CandidateProfile = {
  id: "candidate-1",
  fullName: "Lena Beispiel",
  email: "lena.beispiel@example.com",
  phone: "+49 151 23456789",
  location: "Köln",
  bio: "Sportwissenschaftlerin (M.Sc.) mit Schwerpunkt Trainingswissenschaft und drei Jahren Erfahrung im Athletiktraining im Nachwuchsleistungsbereich Fußball.",
  skills: ["Athletiktraining", "Trainingsplanung", "A-Lizenz", "Datenanalyse"],
  sports: ["Fußball", "Leichtathletik"],
  desiredRoles: ["Athletiktrainer", "Sportwissenschaftler"],
  desiredLocations: ["Köln", "Düsseldorf", "Remote"],
  employmentTypes: ["vollzeit", "werkstudent"],
  documents: [
    {
      id: "doc-1",
      candidateId: "candidate-1",
      type: "cv",
      fileName: "Lebenslauf_Lena_Beispiel.pdf",
      fileUrl: "#",
      uploadedAt: "2026-06-01T10:00:00Z",
    },
    {
      id: "doc-2",
      candidateId: "candidate-1",
      type: "certificate",
      fileName: "A-Lizenz_Zertifikat.pdf",
      fileUrl: "#",
      uploadedAt: "2026-06-01T10:05:00Z",
    },
  ],
  favoriteCompanies: [],
  cvText: null,
  isRecruiter: false,
  createdAt: "2026-05-20T09:00:00Z",
  updatedAt: "2026-06-01T10:05:00Z",
};

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: "app-1",
    candidateId: "candidate-1",
    jobId: "1",
    status: "interview",
    matchScore: 92,
    appliedAt: "2026-06-11T08:30:00Z",
    updatedAt: "2026-06-13T15:00:00Z",
    notes: "Interview am 20.06. um 14 Uhr (online).",
    job: MOCK_JOBS[0],
  },
  {
    id: "app-2",
    candidateId: "candidate-1",
    jobId: "6",
    status: "submitted",
    matchScore: 64,
    appliedAt: "2026-06-13T12:00:00Z",
    updatedAt: "2026-06-13T12:00:00Z",
    notes: null,
    job: MOCK_JOBS[5],
  },
  {
    id: "app-3",
    candidateId: "candidate-1",
    jobId: "2",
    status: "draft",
    matchScore: 48,
    appliedAt: null,
    updatedAt: "2026-06-12T09:00:00Z",
    notes: "Anschreiben noch fertigstellen.",
    job: MOCK_JOBS[1],
  },
];
